# Generated by Django 6.0.4 on 2026-04-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0002_add_scan_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='switch_command',
            field=models.CharField(blank=True, default='show arp', help_text='获取ARP表命令，默认 show arp', max_length=200, verbose_name='ARP命令'),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='task_type',
            field=models.CharField(choices=[('ping', 'Ping 探测'), ('port', '端口扫描'), ('arp', 'ARP 扫描'), ('switch_arp', '交换机ARP获取')], default='ping', max_length=20, verbose_name='任务类型'),
        ),
        migrations.CreateModel(
            name='SwitchDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('vendor', models.CharField(choices=[('cisco', 'Cisco'), ('huawei', 'Huawei'), ('h3c', 'H3C'), ('arista', 'Arista'), ('juniper', 'Juniper')], default='cisco', max_length=20, verbose_name='厂商')),
                ('ip_address', models.GenericIPAddressField(verbose_name='管理IP')),
                ('port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(help_text='支持密码或密钥路径', max_length=200, verbose_name='密码/密钥')),
                ('enable_password', models.CharField(blank=True, default='', help_text='Cisco/Huawei需要enable权限才能执行show命令', max_length=200, verbose_name='Enable特权密码')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='上次成功连接')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='上次错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('subnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_switches', to='ipam.subnet', verbose_name='管理子网')),
            ],
            options={
                'verbose_name': '交换机设备',
                'verbose_name_plural': '交换机设备',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scantask',
            name='switch_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_tasks', to='ipam.switchdevice', verbose_name='目标交换机'),
        ),
    ]
