# Generated by Django 6.0.4 on 2026-04-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcpmgr', '0001_add_lease_and_exclusion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dhcplease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('ip_address',), name='unique_active_ip'),
        ),
    ]
